### ISSUE TITLE
Work with emacs in terminal mode

### ISSUE THREAD

**Issue by mehdipourfar** [progfolio/wordel#4] opened 2022-01-23 21:45 UTC
## Describe the problem
I have nox version of emacs (`apt install emacs-nox`) on my laptop and it seems like wordel doesn't work inside terminal.

This is what I see in the main page:
![wordel](https://user-images.githubusercontent.com/13090047/150698940-f5ea263f-2c29-4203-a08f-e03a7c59c10f.png)

But somehow, help page renders correctly:
![wordel help](https://user-images.githubusercontent.com/13090047/150699002-682cc6a6-e637-4b11-8155-2a4ef4245ea1.png)

## Directions to reproduce
```bash
emacs -nw
```
### Version information

* Emacs version: 27.1
* Org mode version: 9.3
* Operating system: ubuntu focal

**Comment by progfolio** [comment] 2022-01-23 22:33
It works on my system with `emacs -nw`:

![image](https://user-images.githubusercontent.com/44036031/150700606-39567285-c0ee-431f-bcd8-c70399438d4e.png)

I'm not on 27.1, or using emacs-nox, though.
What happens when you try to type/submit a word?
Any errors, or unexpected behavior, or is it just visually off?

**Comment by progfolio** [comment] 2022-01-23 23:28
There was an error on 27.1 specifically with the way I was grabbing user input.
I've pushed a fix. 
However, the game displayed correctly with `emacs -nw` in 27.1.
So the problem may be related to either emacs-nox specifically or something with the terminal emulator being used.
I'm not sure if it will make a difference for you or not, but testing is appreciated.

**Comment by mehdipourfar** [comment] 2022-01-24 08:38
After pulling new code, I can see my inputs but they don't look good. The weird thing is that help page renders with correct colors.
Here is what is see..
![abc](https://user-images.githubusercontent.com/13090047/150748924-334b4e9f-445c-4c3b-9b92-7ab160e08914.png)

**Comment by progfolio** [comment] 2022-01-24 19:41
Ok, I've now tested this in a docker container using Ubuntu focal and emacs27-nox provided via https://launchpad.net/~kelleyk/+archive/ubuntu/emacs

Unfortunately I still don't see the issue. Here's what I see after running `emacs -nw`:

![image](https://user-images.githubusercontent.com/44036031/150851755-03c7a192-94f7-40b8-9540-f4b6cd8ce1b2.png)

Perhaps it has something to do with the terminal emulator you're using or the way it's advertising itself to Emacs?
There's two tests that would be helpful. First, I would also recommend testing this via `emacs -q` to rule out any configuration issues. You'll want to set up the load-path so Emacs can find wordel's files. e.g.

`emacs -q -L /path/to/wordel/ -nw`

Then once you're up and running, `M-x load-library wordel` followed by `M-x wordel`.

If the game board displays correctly at that point, the issue is somewhere in your config.
If not, I would recommend trying a different terminal emulator. I use `sakura` which should be available on your version of Ubuntu via `apt-get install sakura`. Then you can see if the same behavior happens using sakura to launch Emacs.

**Comment by progfolio** [comment] 2022-01-24 19:48
I would also recommend checking the color/display gnome-terminal's display preferences to see if changing options there helps.

**Comment by progfolio** [comment] 2022-02-01 20:58
any luck?

**Comment by mehdipourfar** [comment] 2022-02-01 23:03
I've just find out the issue was with whitespace-mode running with text-mode-hook. By deleting text-mode-hook, it works just fine.

```lisp
(use-package whitespace
  :init
  (dolist (hook '(prog-mode-hook text-mode-hook))
    (add-hook hook #'whitespace-mode))
  (add-hook 'before-save-hook #'whitespace-cleanup)
  :config
  (setq whitespace-line-column 79) ;; limit line length                                                                                                                                                            
  (setq whitespace-style '(face tab empty trailing lines-tail)))
  ```
  
  But Prelude package also adds some hooks for whitespace-mode in text-mode.

**Comment by mehdipourfar** [comment] 2022-02-01 23:09
Anyway, I've been attracted to this project because it's source code seems really clean and I want to learn Elisp. Could you give me some guide about were to start?

**Comment by progfolio** [comment] 2022-02-01 23:31
> I've just find out the issue was with whitespace-mode running with text-mode-hook.

Ah, I see. As a rule of thumb it's always good to test with `emacs -q` to rule out any configuration issues.

>Anyway, I've been attracted to this project because it's source code seems really clean and I want to learn Elisp. Could you give me some guide about were to start?

Thank you.

Where to start depends on your programming experience. If you have no previous programming experience I would recommend reading through "An Introduction to Programming in Emacs Lisp". It should be bundled with your Emacs install and can be accessed via Info (e.g. `C-h i` and then the "Emacs Lisp Intro" node.)

If you're comfortable with the basic concepts of programming in another language and are looking for a comprehensive guide to the features of elisp, Emacs has an Emacs Lisp Reference Manual (accessible through Info as well).

While these are both good resources, you can also learn a lot by looking through other people's source code. It's a good way to take the knowledge gained from the above resources and see how they are applied in practice.

I would start with a simple goal and work toward that. If you have one I could tell you how I would go about implementing it.

**Comment by mehdipourfar** [comment] 2022-02-02 00:14
Thanks a lot. I have an idea but I don't know where to start. I want to add a feature in lsp-mode for golang. In golang, we define functions like this:

func NewHuman(name string,  age int, weight int, height int)

And we call them like this:

NewHuman("some name", 10, 100, 90)

and as you can see, when we look at the line above, we are not sure if 100 is weight or height? I want to some mode or something which can display the last line in this format:

NewHuman(_name:_ "some name", _age:_ 10, _weight:_ 100, _height:_ 90)

I'll try Emacs Lisp manual. Thanks for your help.

**Comment by progfolio** [comment] 2022-02-02 00:18
Sounds good. Best of luck.

**Closed as completed by progfolio** 2022-02-02 00:18 UTC
Labels: bug
